# Generated by Django 3.0.7 on 2020-06-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='todo.Category')),
            ],
        ),
    ]
